multiple improvements

diff --git a/conf/lamp b/conf/lamp
--- a/conf/lamp
+++ b/conf/lamp
@@ -143,8 +143,7 @@ lamp_status() {
 lamp_kill() {
     echo "Kill apache,mysql process..."
     killall httpd
-    killall mysql
-    killall mariadb
+    killall mysqld mariadbd 2>/dev/null
     echo "done."
 }
 
@@ -188,7 +187,7 @@ Function_Database() {
             exit 1
             ;;
         *)
-            echo "Usage: lamp database {add|list|del}"
+            echo "Usage: lamp database {add|list|edit|del}"
             exit 1
             ;;
 esac
@@ -422,7 +421,7 @@ Add_VHost() {
 
 List_VHost() {
     echo "Apache Virtualhost list:"
-    ls /usr/local/apache/conf/vhost/ | grep ".conf$" | sed 's/.conf//g'
+    ls /usr/local/apache/conf/vhost/ | grep ".conf$" | sed 's/\.conf$//'
 }
 
 Del_VHost() {
@@ -449,6 +448,7 @@ Del_VHost() {
         exit 1
     else
         rm -f /usr/local/apache/conf/vhost/${domain}.conf
+        /usr/local/apache/bin/apachectl configtest && systemctl restart httpd
         echo "========================================================"
         echo "Domain: ${domain} has been deleted."
         echo "Website files will not be deleted for security reasons."
@@ -472,12 +472,20 @@ Check_DB() {
 }
 
 Make_TempMycnf() {
-    cat >~/.my.cnf <<EOF
+    if [ -z "${_mycnf_backup+set}" ]; then
+        if [ -f ${HOME}/.my.cnf ]; then
+            _mycnf_backup="$(mktemp /tmp/.lnmp_mycnf_bak.XXXXXX)"
+            cp -p ${HOME}/.my.cnf "${_mycnf_backup}"
+        else
+            _mycnf_backup=""
+        fi
+    fi
+    cat >${HOME}/.my.cnf <<EOF
 [client]
 user=root
 password='$1'
 EOF
-    chmod 600 ~/.my.cnf
+    chmod 600 ${HOME}/.my.cnf
     trap 'TempMycnf_Clean' EXIT
     trap 'TempMycnf_Clean; exit 1' INT TERM HUP
 }
@@ -490,7 +498,7 @@ Verify_DB_Password() {
     status=1
     while [ $status -eq 1 ]; do
         Echo_Yellow "Enter current root password of Database (Password will not shown): "
-        read -s DB_Root_Password
+        read -r -s DB_Root_Password
         echo
         Make_TempMycnf "${DB_Root_Password}"
         Do_Query ""
@@ -503,14 +511,18 @@ Do_Query() {
     echo "$1" >/tmp/.mysql.tmp
     chmod 600 /tmp/.mysql.tmp
     Check_DB || return 1
-    ${MySQL_Bin} --defaults-file=~/.my.cnf </tmp/.mysql.tmp
+    ${MySQL_Bin} --defaults-file=${HOME}/.my.cnf </tmp/.mysql.tmp
     return $?
 }
 
 TempMycnf_Clean() {
-    if [ -s ~/.my.cnf ]; then
-        rm -f ~/.my.cnf
+    if [ -n "${_mycnf_backup}" ] && [ -f "${_mycnf_backup}" ]; then
+        mv "${_mycnf_backup}" ${HOME}/.my.cnf
+    elif [ -s ${HOME}/.my.cnf ]; then
+        rm -f ${HOME}/.my.cnf
     fi
+    unset _mycnf_backup
+    trap - EXIT INT TERM HUP
     if [ -s /tmp/.mysql.tmp ]; then
         rm -f /tmp/.mysql.tmp
     fi
@@ -543,8 +555,7 @@ Add_Database_Menu() {
 }
 
 Add_Database() {
-    if echo "${MySQL_Ver}" | grep -Eqi '^8.(0|4).'; then
-        cat >/tmp/.add_mysql.sql <<EOF
+    cat >/tmp/.add_mysql.sql <<EOF
 CREATE DATABASE IF NOT EXISTS \`${database_name}\`;
 CREATE USER IF NOT EXISTS '${database_name}'@'localhost' IDENTIFIED BY '${mysql_password}';
 CREATE USER IF NOT EXISTS '${database_name}'@'127.0.0.1' IDENTIFIED BY '${mysql_password}';
@@ -552,25 +563,13 @@ GRANT ALL PRIVILEGES ON \`${database_name}\`.* TO '${database_name}'@'localhost'
 GRANT ALL PRIVILEGES ON \`${database_name}\`.* TO '${database_name}'@'127.0.0.1';
 FLUSH PRIVILEGES;
 EOF
-
-    else
-        cat >/tmp/.add_mysql.sql <<EOF
-CREATE DATABASE IF NOT EXISTS \`${database_name}\`;
-CREATE USER IF NOT EXISTS '${database_name}'@'localhost' IDENTIFIED BY '${mysql_password}';
-CREATE USER IF NOT EXISTS '${database_name}'@'127.0.0.1' IDENTIFIED BY '${mysql_password}';
-GRANT ALL PRIVILEGES ON \`${database_name}\`.* TO '${database_name}'@'localhost';
-GRANT ALL PRIVILEGES ON \`${database_name}\`.* TO '${database_name}'@'127.0.0.1';
-FLUSH PRIVILEGES;
-EOF
-
-    fi
-    ${MySQL_Bin} --defaults-file=~/.my.cnf </tmp/.add_mysql.sql
+    ${MySQL_Bin} --defaults-file=${HOME}/.my.cnf </tmp/.add_mysql.sql
     [ $? -eq 0 ] && echo "Add database Sucessfully." || echo "Add database failed!"
     rm -f /tmp/.add_mysql.sql
 }
 
 List_Database() {
-    ${MySQL_Bin} --defaults-file=~/.my.cnf -e "SHOW DATABASES;"
+    ${MySQL_Bin} --defaults-file=${HOME}/.my.cnf -e "SHOW DATABASES;"
     [ $? -eq 0 ] && echo "List all databases Sucessfully." || echo "List all databases failed!"
 }
 
@@ -598,10 +597,11 @@ Edit_Database() {
         fi
     done
 
-    Do_Query "ALTER USER '${database_username}'@'127.0.0.1' IDENTIFIED BY '${database_username_passwd}';"
-    Do_Query "ALTER USER '${database_username}'@'localhost' IDENTIFIED BY '${database_username_passwd}';"
-    [ $? -eq 0 ] && echo "Edit user password Sucessfully." || echo "Edit user password databases failed!"
-    Do_Query "FLUSH PRIVILEGES;"
+    edit_status=0
+    Do_Query "ALTER USER '${database_username}'@'127.0.0.1' IDENTIFIED BY '${database_username_passwd}';" || edit_status=1
+    Do_Query "ALTER USER '${database_username}'@'localhost' IDENTIFIED BY '${database_username_passwd}';" || edit_status=1
+    Do_Query "FLUSH PRIVILEGES;" || edit_status=1
+    [ ${edit_status} -eq 0 ] && echo "Edit user password Sucessfully." || echo "Edit user password databases failed!"
 }
 
 Del_Database() {
@@ -620,7 +620,7 @@ DROP USER '${database_name}'@'localhost';
 DROP DATABASE \`${database_name}\`;
 FLUSH PRIVILEGES;
 EOF
-    ${MySQL_Bin} --defaults-file=~/.my.cnf </tmp/.del.mysql.sql
+    ${MySQL_Bin} --defaults-file=${HOME}/.my.cnf </tmp/.del.mysql.sql
     [ $? -eq 0 ] && echo "Delete database: ${database_name} Sucessfully." || echo "Delete database: ${database_name} failed!"
     rm -f /tmp/.del.mysql.sql
 }
@@ -819,7 +819,7 @@ Check_Acme_EMail() {
         while :; do
             Echo_Yellow "Please enter your email address: "
             read -r email_address
-            if [[ "${email_address}" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$ ]]; then
+            if [[ "${email_address}" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]; then
                 echo "Email address ${email_address} is valid."
                 break
             else
@@ -929,7 +929,7 @@ Add_SSL_Menu() {
                 fi
             done
             break
-        elif [[ "${ssl_choice}" =~ [234] ]]; then
+        elif [[ "${ssl_choice}" =~ ^[234]$ ]]; then
             Check_Acme_EMail
             break
         else
@@ -947,12 +947,11 @@ Install_Check_Acme.sh() {
             /usr/local/acme.sh/acme.sh --register-account -m ${email_address}
         fi
     else
-        cd /tmp
-        git clone --depth 1 https://github.com/acmesh-official/acme.sh.git
-        cd acme.sh
+        rm -rf /tmp/acme.sh
+        git clone --depth 1 https://github.com/acmesh-official/acme.sh.git /tmp/acme.sh
+        cd /tmp/acme.sh || exit 1
         ./acme.sh --install ${acme_sh_sudo} --log --home /usr/local/acme.sh -m ${email_address}
-        cd ..
-        rm -rf acme.sh
+        rm -rf /tmp/acme.sh
     fi
     # set deaulft CA Server to letsencrypt
     #/usr/local/acme.sh/acme.sh --set-default-ca --server letsencrypt
@@ -1163,8 +1162,8 @@ Add_Dns_SSL() {
         /usr/local/acme.sh/acme.sh ${acme_sh_sudo} --renew ${letsdomain} --yes-I-know-dns-manual-mode-enough-go-ahead-please
         lets_status=$?
     fi
-    Install_SSL_Cert
     if [ "${lets_status}" = 0 ] || [[ "${provider}" = "" && "${lets_status}" = 1 && -s "/usr/local/apache/conf/ssl/${domain}/${domain}.cer" ]]; then
+        Install_SSL_Cert
         if [ ! -d "${vhostdir}" ]; then
             echo "Create Virtul Host directory......"
             mkdir -p "${vhostdir}"
@@ -1248,8 +1247,8 @@ Add_Dns_SSL_Only() {
         /usr/local/acme.sh/acme.sh ${acme_sh_sudo} --renew ${letsdomain} --yes-I-know-dns-manual-mode-enough-go-ahead-please
         lets_status=$?
     fi
-    Install_SSL_Cert
     if [ "${lets_status}" = 0 ] || [[ "${provider}" = "" && "${lets_status}" = 1 && -s "/usr/local/apache/conf/ssl/${domain}/${domain}.cer" ]]; then
+        Install_SSL_Cert
         Echo_Blue "------------------ SSL Certificate information as follows ------------------"
         Echo_Blue "| Domain: ${domain} ${moredomain}"
         Echo_Blue "| SSL Certificate: /usr/local/apache/conf/ssl/${domain}/${domain}.cer"
@@ -1266,19 +1265,19 @@ Color_Text() {
 }
 
 Echo_Red() {
-  echo $(Color_Text "$1" "31")
+  echo "$(Color_Text "$1" "31")"
 }
 
 Echo_Green() {
-  echo $(Color_Text "$1" "32")
+  echo "$(Color_Text "$1" "32")"
 }
 
 Echo_Yellow() {
-  echo -n $(Color_Text "$1" "33")
+  echo -n "$(Color_Text "$1" "33")"
 }
 
 Echo_Blue() {
-  echo $(Color_Text "$1" "34")
+  echo "$(Color_Text "$1" "34")"
 }
 
 Sleep_Sec() {
@@ -1314,17 +1313,38 @@ case "${arg1}" in
     status)
         lamp_status
         ;;
-    mysql)
-        systemctl ${arg2} mysql
-        ;;
-    mariadb)
-        systemctl ${arg2} mariadb
+    mysql|mariadb)
+        case "${arg2}" in
+        start|stop|restart|reload|status)
+            lamp_db_control "${arg2}"
+            ;;
+        *)
+            echo "Usage: lamp mysql {start|stop|restart|reload|status}"
+            exit 1
+            ;;
+        esac
         ;;
     pureftpd)
-        systemctl ${arg2} pureftpd
+        case "${arg2}" in
+        start|stop|restart|reload|status)
+            systemctl ${arg2} pureftpd
+            ;;
+        *)
+            echo "Usage: lamp pureftpd {start|stop|restart|reload|status}"
+            exit 1
+            ;;
+        esac
         ;;
     httpd)
-        systemctl ${arg2} httpd
+        case "${arg2}" in
+        start|stop|restart|reload|status)
+            systemctl ${arg2} httpd
+            ;;
+        *)
+            echo "Usage: lamp httpd {start|stop|restart|reload|status}"
+            exit 1
+            ;;
+        esac
         ;;
     vhost)
         Function_Vhost ${arg2}
diff --git a/conf/lnmp b/conf/lnmp
--- a/conf/lnmp
+++ b/conf/lnmp
@@ -185,8 +185,7 @@ lnmp_status() {
 lnmp_kill() {
     echo "Kill nginx,php-fpm,mysql process..."
     killall nginx
-    killall mysql
-    killall mariadb
+    killall mysqld mariadbd 2>/dev/null
     killall php-fpm
     echo "done."
 }
@@ -231,7 +230,7 @@ Function_Database() {
         exit 1
         ;;
     *)
-        echo "Usage: lnmp database {add|list|del}"
+        echo "Usage: lnmp database {add|list|edit|del}"
         exit 1
         ;;
     esac
@@ -328,7 +327,7 @@ EOF
 }
 
 Multiple_PHP_Select() {
-    if [[ ! -s /usr/local/php5.2/sbin/php-fpm && ! -s /usr/local/nginx/conf/enable-php5.2.conf ]] && [[ ! -s /usr/local/php5.3/sbin/php-fpm && ! -s /usr/local/nginx/conf/enable-php5.3.conf ]] && [[ ! -s /usr/local/php5.4/sbin/php-fpm && ! -s /usr/local/nginx/conf/enable-php5.4.conf ]] && [[ ! -s /usr/local/php5.5/sbin/php-fpm && ! -s /usr/local/nginx/conf/enable-php5.5.conf ]] && [[ ! -s /usr/local/php5.6/sbin/php-fpm && ! -s /usr/local/nginx/conf/enable-php5.6.conf ]] && [[ ! -s /usr/local/php7.0/sbin/php-fpm && ! -s /usr/local/nginx/conf/enable-php7.0.conf ]] && [[ ! -s /usr/local/php7.1/sbin/php-fpm && ! -s /usr/local/nginx/conf/enable-php7.1.conf ]] && [[ ! -s /usr/local/php7.2/sbin/php-fpm && ! -s /usr/local/nginx/conf/enable-php7.2.conf ]] && [[ ! -s /usr/local/php7.3/sbin/php-fpm && ! -s /usr/local/nginx/conf/enable-php7.3.conf ]] && [[ ! -s /usr/local/php7.4/sbin/php-fpm && ! -s /usr/local/nginx/conf/enable-php7.4.conf ]] && [[ ! -s /usr/local/php8.0/sbin/php-fpm && ! -s /usr/local/nginx/conf/enable-php8.0.conf ]] && [[ ! -s /usr/local/php8.1/sbin/php-fpm && ! -s /usr/local/nginx/conf/enable-php8.1.conf ]] && [[ ! -s /usr/local/php8.2/sbin/php-fpm && ! -s /usr/local/nginx/conf/enable-php8.2.conf ]]; then
+    if [[ ! -s /usr/local/php7.2/sbin/php-fpm ]] && [[ ! -s /usr/local/php7.3/sbin/php-fpm ]] && [[ ! -s /usr/local/php7.4/sbin/php-fpm ]] && [[ ! -s /usr/local/php8.0/sbin/php-fpm ]] && [[ ! -s /usr/local/php8.1/sbin/php-fpm ]] && [[ ! -s /usr/local/php8.2/sbin/php-fpm ]] && [[ ! -s /usr/local/php8.3/sbin/php-fpm ]] && [[ ! -s /usr/local/php8.4/sbin/php-fpm ]] && [[ ! -s /usr/local/php8.5/sbin/php-fpm ]]; then
         if [ "${enable_pathinfo}" == "y" ]; then
             include_enable_php="include enable-php-pathinfo.conf;"
         else
@@ -338,27 +337,27 @@ Multiple_PHP_Select() {
         echo "Multiple PHP version found, Please select the PHP version."
         Cur_PHP_Version="$(/usr/local/php/bin/php-config --version)"
         Echo_Green "1: Default Main PHP ${Cur_PHP_Version}"
-#        if [[ -s /usr/local/php5.2/sbin/php-fpm && -s /usr/local/nginx/conf/enable-php5.2.conf && -s /etc/systemd/system/php-fpm5.2.service ]]; then
-#            Echo_Green "2: PHP 5.2 [found]"
-#        fi
-#        if [[ -s /usr/local/php5.3/sbin/php-fpm && -s /usr/local/nginx/conf/enable-php5.3.conf && -s /etc/systemd/system/php-fpm5.3.service ]]; then
-#            Echo_Green "3: PHP 5.3 [found]"
-#        fi
-#        if [[ -s /usr/local/php5.4/sbin/php-fpm && -s /usr/local/nginx/conf/enable-php5.4.conf && -s /etc/systemd/system/php-fpm5.4.service ]]; then
-#            Echo_Green "4: PHP 5.4 [found]"
-#        fi
-#        if [[ -s /usr/local/php5.5/sbin/php-fpm && -s /usr/local/nginx/conf/enable-php5.5.conf && -s /etc/systemd/system/php-fpm5.5.service ]]; then
-#            Echo_Green "5: PHP 5.5 [found]"
-#        fi
-        if [[ -s /usr/local/php5.6/sbin/php-fpm && -s /usr/local/nginx/conf/enable-php5.6.conf && -s /etc/systemd/system/php-fpm5.6.service ]]; then
-            Echo_Green "6: PHP 5.6 [found]"
-        fi
-        if [[ -s /usr/local/php7.0/sbin/php-fpm && -s /usr/local/nginx/conf/enable-php7.0.conf && -s /etc/systemd/system/php-fpm7.0.service ]]; then
-            Echo_Green "7: PHP 7.0 [found]"
-        fi
-        if [[ -s /usr/local/php7.1/sbin/php-fpm && -s /usr/local/nginx/conf/enable-php7.1.conf && -s /etc/systemd/system/php-fpm7.1.service ]]; then
-            Echo_Green "8: PHP 7.1 [found]"
-        fi
+        # if [[ -s /usr/local/php5.2/sbin/php-fpm && -s /usr/local/nginx/conf/enable-php5.2.conf && -s /etc/systemd/system/php-fpm5.2.service ]]; then
+        #     Echo_Green "2: PHP 5.2 [found]"
+        # fi
+        # if [[ -s /usr/local/php5.3/sbin/php-fpm && -s /usr/local/nginx/conf/enable-php5.3.conf && -s /etc/systemd/system/php-fpm5.3.service ]]; then
+        #     Echo_Green "3: PHP 5.3 [found]"
+        # fi
+        # if [[ -s /usr/local/php5.4/sbin/php-fpm && -s /usr/local/nginx/conf/enable-php5.4.conf && -s /etc/systemd/system/php-fpm5.4.service ]]; then
+        #     Echo_Green "4: PHP 5.4 [found]"
+        # fi
+        # if [[ -s /usr/local/php5.5/sbin/php-fpm && -s /usr/local/nginx/conf/enable-php5.5.conf && -s /etc/systemd/system/php-fpm5.5.service ]]; then
+        #     Echo_Green "5: PHP 5.5 [found]"
+        # fi
+        # if [[ -s /usr/local/php5.6/sbin/php-fpm && -s /usr/local/nginx/conf/enable-php5.6.conf && -s /etc/systemd/system/php-fpm5.6.service ]]; then
+        #     Echo_Green "6: PHP 5.6 [found]"
+        # fi
+        # if [[ -s /usr/local/php7.0/sbin/php-fpm && -s /usr/local/nginx/conf/enable-php7.0.conf && -s /etc/systemd/system/php-fpm7.0.service ]]; then
+        #     Echo_Green "7: PHP 7.0 [found]"
+        # fi
+        # if [[ -s /usr/local/php7.1/sbin/php-fpm && -s /usr/local/nginx/conf/enable-php7.1.conf && -s /etc/systemd/system/php-fpm7.1.service ]]; then
+        #     Echo_Green "8: PHP 7.1 [found]"
+        # fi
         if [[ -s /usr/local/php7.2/sbin/php-fpm && -s /usr/local/nginx/conf/enable-php7.2.conf && -s /etc/systemd/system/php-fpm7.2.service ]]; then
             Echo_Green "9: PHP 7.2 [found]"
         fi
@@ -386,7 +385,7 @@ Multiple_PHP_Select() {
         if [[ -s /usr/local/php8.5/sbin/php-fpm && -s /usr/local/nginx/conf/enable-php8.5.conf && -s /etc/systemd/system/php-fpm8.5.service ]]; then
             Echo_Green "17: PHP 8.5 [found]"
         fi
-        Echo_Yellow "Enter your choice (6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 or 17): "
+        Echo_Yellow "Enter your choice (1, 9, 10, 11, 12, 13, 14, 15, 16 or 17): "
         read -r php_select
         case "${php_select}" in
         1)
@@ -741,7 +740,7 @@ Add_VHost() {
 
     Add_VHost_Config || exit 1
 
-    systemctl reload php-fpm
+    lnmp_phpfpm_control reload
 
     if [ "${create_database}" == "y" ]; then
         Add_Database
@@ -801,7 +800,7 @@ Add_VHost() {
 
 List_VHost() {
     echo "Nginx Virtualhost list:"
-    ls /usr/local/nginx/conf/vhost/ | grep ".conf$" | sed 's/.conf//g'
+    ls /usr/local/nginx/conf/vhost/ | grep ".conf$" | sed 's/\.conf$//'
 }
 
 Del_VHost() {
@@ -827,11 +826,14 @@ Del_VHost() {
         echo "=========================================="
         exit 1
     else
+        vhostdir=$(grep -oP 'root\s+\K[^;]+' /usr/local/nginx/conf/vhost/${domain}.conf | head -1)
         if [ -f "${vhostdir}/.user.ini" ]; then
             chattr -i "${vhostdir}/.user.ini"
             rm -f "${vhostdir}/.user.ini"
         fi
         rm -f /usr/local/nginx/conf/vhost/${domain}.conf
+        echo "Test Nginx configure file......"
+        /usr/local/nginx/sbin/nginx -t && /usr/local/nginx/sbin/nginx -s reload
         echo "========================================================"
         echo "Domain: ${domain} has been deleted."
         echo "Website files will not be deleted for security reasons."
@@ -855,12 +857,20 @@ Check_DB() {
 }
 
 Make_TempMycnf() {
-    cat >~/.my.cnf <<EOF
+    if [ -z "${_mycnf_backup+set}" ]; then
+        if [ -f ${HOME}/.my.cnf ]; then
+            _mycnf_backup="$(mktemp /tmp/.lnmp_mycnf_bak.XXXXXX)"
+            cp -p ${HOME}/.my.cnf "${_mycnf_backup}"
+        else
+            _mycnf_backup=""
+        fi
+    fi
+    cat >${HOME}/.my.cnf <<EOF
 [client]
 user=root
 password='$1'
 EOF
-    chmod 600 ~/.my.cnf
+    chmod 600 ${HOME}/.my.cnf
     trap 'TempMycnf_Clean' EXIT
     trap 'TempMycnf_Clean; exit 1' INT TERM HUP
 }
@@ -873,7 +883,7 @@ Verify_DB_Password() {
     status=1
     while [ $status -eq 1 ]; do
         Echo_Yellow "Enter current root password of Database (Password will not shown): "
-        read -s DB_Root_Password
+        read -r -s DB_Root_Password
         echo
         Make_TempMycnf "${DB_Root_Password}"
         Do_Query ""
@@ -886,14 +896,18 @@ Do_Query() {
     echo "$1" >/tmp/.mysql.tmp
     chmod 600 /tmp/.mysql.tmp
     Check_DB || return 1
-    ${MySQL_Bin} --defaults-file=~/.my.cnf </tmp/.mysql.tmp
+    ${MySQL_Bin} --defaults-file=${HOME}/.my.cnf </tmp/.mysql.tmp
     return $?
 }
 
 TempMycnf_Clean() {
-    if [ -s ~/.my.cnf ]; then
-        rm -f ~/.my.cnf
+    if [ -n "${_mycnf_backup}" ] && [ -f "${_mycnf_backup}" ]; then
+        mv "${_mycnf_backup}" ${HOME}/.my.cnf
+    elif [ -s ${HOME}/.my.cnf ]; then
+        rm -f ${HOME}/.my.cnf
     fi
+    unset _mycnf_backup
+    trap - EXIT INT TERM HUP
     if [ -s /tmp/.mysql.tmp ]; then
         rm -f /tmp/.mysql.tmp
     fi
@@ -926,8 +940,7 @@ Add_Database_Menu() {
 }
 
 Add_Database() {
-    if echo "${MySQL_Ver}" | grep -Eqi '^8.(0|4).'; then
-        cat >/tmp/.add_mysql.sql <<EOF
+    cat >/tmp/.add_mysql.sql <<EOF
 CREATE DATABASE IF NOT EXISTS \`${database_name}\`;
 CREATE USER IF NOT EXISTS '${database_name}'@'localhost' IDENTIFIED BY '${mysql_password}';
 CREATE USER IF NOT EXISTS '${database_name}'@'127.0.0.1' IDENTIFIED BY '${mysql_password}';
@@ -935,25 +948,13 @@ GRANT ALL PRIVILEGES ON \`${database_name}\`.* TO '${database_name}'@'localhost'
 GRANT ALL PRIVILEGES ON \`${database_name}\`.* TO '${database_name}'@'127.0.0.1';
 FLUSH PRIVILEGES;
 EOF
-
-    else
-        cat >/tmp/.add_mysql.sql <<EOF
-CREATE DATABASE IF NOT EXISTS \`${database_name}\`;
-CREATE USER IF NOT EXISTS '${database_name}'@'localhost' IDENTIFIED BY '${mysql_password}';
-CREATE USER IF NOT EXISTS '${database_name}'@'127.0.0.1' IDENTIFIED BY '${mysql_password}';
-GRANT ALL PRIVILEGES ON \`${database_name}\`.* TO '${database_name}'@'localhost';
-GRANT ALL PRIVILEGES ON \`${database_name}\`.* TO '${database_name}'@'127.0.0.1';
-FLUSH PRIVILEGES;
-EOF
-
-    fi
-    ${MySQL_Bin} --defaults-file=~/.my.cnf </tmp/.add_mysql.sql
+    ${MySQL_Bin} --defaults-file=${HOME}/.my.cnf </tmp/.add_mysql.sql
     [ $? -eq 0 ] && echo "Add database Sucessfully." || echo "Add database failed!"
     rm -f /tmp/.add_mysql.sql
 }
 
 List_Database() {
-    ${MySQL_Bin} --defaults-file=~/.my.cnf -e "SHOW DATABASES;"
+    ${MySQL_Bin} --defaults-file=${HOME}/.my.cnf -e "SHOW DATABASES;"
     [ $? -eq 0 ] && echo "List all databases Sucessfully." || echo "List all databases failed!"
 }
 
@@ -981,10 +982,11 @@ Edit_Database() {
         fi
     done
 
-    Do_Query "ALTER USER '${database_username}'@'127.0.0.1' IDENTIFIED BY '${database_username_passwd}';"
-    Do_Query "ALTER USER '${database_username}'@'localhost' IDENTIFIED BY '${database_username_passwd}';"
-    [ $? -eq 0 ] && echo "Edit user password Sucessfully." || echo "Edit user password databases failed!"
-    Do_Query "FLUSH PRIVILEGES;"
+    edit_status=0
+    Do_Query "ALTER USER '${database_username}'@'127.0.0.1' IDENTIFIED BY '${database_username_passwd}';" || edit_status=1
+    Do_Query "ALTER USER '${database_username}'@'localhost' IDENTIFIED BY '${database_username_passwd}';" || edit_status=1
+    Do_Query "FLUSH PRIVILEGES;" || edit_status=1
+    [ ${edit_status} -eq 0 ] && echo "Edit user password Sucessfully." || echo "Edit user password databases failed!"
 }
 
 Del_Database() {
@@ -1003,7 +1005,7 @@ DROP USER '${database_name}'@'localhost';
 DROP DATABASE \`${database_name}\`;
 FLUSH PRIVILEGES;
 EOF
-    ${MySQL_Bin} --defaults-file=~/.my.cnf </tmp/.del.mysql.sql
+    ${MySQL_Bin} --defaults-file=${HOME}/.my.cnf </tmp/.del.mysql.sql
     [ $? -eq 0 ] && echo "Delete database: ${database_name} Sucessfully." || echo "Delete database: ${database_name} failed!"
     rm -f /tmp/.del.mysql.sql
 }
@@ -1205,7 +1207,7 @@ Add_SSL_Info_Menu() {
     read -r enable_pathinfo
     if [[ "${enable_pathinfo}" == "n" || "${enable_pathinfo}" == "" ]]; then
         echo "Disable pathinfo."
-    elif [ "${allow_rewrite}" == "y" ]; then
+    elif [ "${enable_pathinfo}" == "y" ]; then
         echo "Enable pathinfo."
         enable_pathinfo="y"
     fi
@@ -1228,7 +1230,7 @@ Check_Acme_EMail() {
         while :; do
             Echo_Yellow "Please enter your email address: "
             read -r email_address
-            if [[ "${email_address}" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$ ]]; then
+            if [[ "${email_address}" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]; then
                 echo "Email address ${email_address} is valid."
                 break
             else
@@ -1342,12 +1344,11 @@ Install_Check_Acme.sh() {
             /usr/local/acme.sh/acme.sh --register-account -m ${email_address}
         fi
     else
-        cd /tmp
-        git clone --depth 1 https://github.com/acmesh-official/acme.sh.git
-        cd acme.sh
+        rm -rf /tmp/acme.sh
+        git clone --depth 1 https://github.com/acmesh-official/acme.sh.git /tmp/acme.sh
+        cd /tmp/acme.sh || exit 1
         ./acme.sh --install ${acme_sh_sudo} --log --home /usr/local/acme.sh -m ${email_address}
-        cd ..
-        rm -rf acme.sh
+        rm -rf /tmp/acme.sh
     fi
     # set deaulft CA Server to letsencrypt
     #/usr/local/acme.sh/acme.sh --set-default-ca --server letsencrypt
@@ -1373,7 +1374,7 @@ server
     {
         listen 443 ssl;
         #listen [::]:443 ssl;
-        http2 on;
+        http2 on; # requires nginx >= 1.25.1; installer always ships the latest nginx so this is intentional
         server_name ${domain} ${moredomain};
         index index.html index.htm index.php default.html default.htm default.php;
         root  ${vhostdir};
@@ -1578,8 +1579,8 @@ Add_Dns_SSL() {
         /usr/local/acme.sh/acme.sh ${acme_sh_sudo} --renew ${letsdomain} --yes-I-know-dns-manual-mode-enough-go-ahead-please
         lets_status=$?
     fi
-    Install_SSL_Cert
     if [ "${lets_status}" = 0 ] || [[ "${provider}" = "" && "${lets_status}" = 1 && -s "/usr/local/nginx/conf/ssl/${domain}/fullchain.cer" ]]; then
+        Install_SSL_Cert
         if [ ! -d "${vhostdir}" ]; then
             echo "Create Virtul Host directory......"
             mkdir -p "${vhostdir}"
@@ -1663,8 +1664,8 @@ Add_Dns_SSL_Only() {
         /usr/local/acme.sh/acme.sh ${acme_sh_sudo} --renew ${letsdomain} --yes-I-know-dns-manual-mode-enough-go-ahead-please
         lets_status=$?
     fi
-    Install_SSL_Cert
     if [ "${lets_status}" = 0 ] || [[ "${provider}" = "" && "${lets_status}" = 1 && -s "/usr/local/nginx/conf/ssl/${domain}/fullchain.cer" ]]; then
+        Install_SSL_Cert
         Echo_Blue "------------------ SSL Certificate information as follows ------------------"
         Echo_Blue "| Domain: ${domain} ${moredomain}"
         Echo_Blue "| SSL Certificate: /usr/local/nginx/conf/ssl/${domain}/fullchain.cer"
@@ -1681,19 +1682,19 @@ Color_Text() {
 }
 
 Echo_Red() {
-    echo $(Color_Text "$1" "31")
+    echo "$(Color_Text "$1" "31")"
 }
 
 Echo_Green() {
-    echo $(Color_Text "$1" "32")
+    echo "$(Color_Text "$1" "32")"
 }
 
 Echo_Yellow() {
-    echo -n $(Color_Text "$1" "33")
+    echo -n "$(Color_Text "$1" "33")"
 }
 
 Echo_Blue() {
-    echo $(Color_Text "$1" "34")
+    echo "$(Color_Text "$1" "34")"
 }
 
 Sleep_Sec() {
@@ -1730,19 +1731,48 @@ status)
     lnmp_status
     ;;
 nginx)
-    systemctl ${arg2} nginx
+    case "${arg2}" in
+    start|stop|restart|reload|status)
+        systemctl ${arg2} nginx
+        ;;
+    *)
+        echo "Usage: lnmp nginx {start|stop|restart|reload|status}"
+        exit 1
+        ;;
+    esac
     ;;
-mysql)
-    systemctl ${arg2} mysql
-    ;;
-mariadb)
-    systemctl ${arg2} mariadb
+mysql|mariadb)
+    case "${arg2}" in
+    start|stop|restart|reload|status)
+        lnmp_db_control "${arg2}"
+        ;;
+    *)
+        echo "Usage: lnmp mysql {start|stop|restart|reload|status}"
+        exit 1
+        ;;
+    esac
     ;;
 php-fpm)
-    systemctl ${arg2} php-fpm
+    case "${arg2}" in
+    start|stop|restart|reload|status)
+        lnmp_phpfpm_control "${arg2}"
+        ;;
+    *)
+        echo "Usage: lnmp php-fpm {start|stop|restart|reload|status}"
+        exit 1
+        ;;
+    esac
     ;;
 pureftpd)
-    systemctl ${arg2} pureftpd
+    case "${arg2}" in
+    start|stop|restart|reload|status)
+        systemctl ${arg2} pureftpd
+        ;;
+    *)
+        echo "Usage: lnmp pureftpd {start|stop|restart|reload|status}"
+        exit 1
+        ;;
+    esac
     ;;
 vhost)
     Function_Vhost ${arg2}
